name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # trigger installation from rust-toolchain.toml
      - name: Setup rust toolchain
        run: rustup show

      - name: Setup rust cache
        uses: Swatinem/rust-cache@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --no-upgrade --no-install-recommends -y llvm-14-tools qemu-system-x86

      - name: Install bootimage
        run: cargo install bootimage

      - name: Run tests
        run: cargo test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # trigger installation from rust-toolchain.toml
      - name: Setup rust toolchain
        run: rustup show

      - name: Run Clippy linter
        run: cargo clippy --tests -- -D warnings

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # trigger installation from rust-toolchain.toml
      - name: Setup rust toolchain
        run: rustup show

      - name: Check formatting
        run: cargo fmt -- --check
